### ISSUE TITLE
Where can I get csv files from?

### ISSUE THREAD

**Issue by markjfisher** [troydm/edda#1]
I'm trying to setup a local commodities REST API to query prices against, as I can't find anything online, and came across this project.

The instructions say to download initial static data from:

    curl -O https://raw.githubusercontent.com/jamesremuscat/EDDN/master/doc/commodity.csv

This is now 404, but is there another source?
Same goes for the outfitting and shipyard files.

**Comment by markjfisher** [comment]
I used the ones from

    https://raw.githubusercontent.com/EDCD/FDevIDs/master/commodity.csv

etc instead. Still trying to get ` stack exec edda -- import -s eddb -t stations` to work

**Comment by markjfisher** [comment]
I've turned auth off on my db for now to try and get this working. I imported the csv files from the above location, but now importing systems/stations is failing. What do I need to setup or change to get this working?

    $ stack exec edda -- import -s eddb -t systems
    Downloading EDDB Systems data...
    EDDB Systems data downloaded
    Total systems imported: 0

    $ stack exec edda -- import -s eddb -t stations
    Loading EDDB modules list
    Downloading EDDB modules...
    EDDB Modules downloaded
    Loading EDDB systems id map
    EDDB systems id map loaded: 0
    Downloading EDDB Stations data...
    EDDB Stations data downloaded
    Total stations imported: 0
    Downloading EDDB commodities...
    Couldn't import commodities

**Comment by markjfisher** [comment]
OK, after looking at the source, it has references to files and URLs that don't exist anymore, e.g. systems.json (replaced with systems.jsonl), and https://eddb.io/archive/v4/stations.json etc.

I take it this project is no longer functional? Any suggestions for an alternative?

**Comment by troydm** [comment]
I haven't updated it in a while, yeah probably some things changed and now it doesn't works, I'll probably take a look later when I have free time, if it's only changed url you can probably just change it but I doubt it since jsonl format is compressed data it needs some code modifications to work with it

**Comment by troydm** [comment]
@markjfisher I've made a huge update to edda, please get the latest version and try following instructions from scratch, everything should work now, in case something is not working let me know
