### ISSUE TITLE
edda db, import, and url error

### ISSUE THREAD

**Issue by cs1ga** [troydm/edda#3]
Hi,

Edda is nit working correctly.
1) The url is wrong:

Stations.hs
url = "https://eddb.io/archive/v5/stations.json"
module_url = "https://eddb.io/archive/v5/modules.json"
listings_url = "https://eddb.io/archive/v5/listings.csv"
commodities_url = "https://eddb.io/archive/v5/commodities.json"

Systems.sh
url = "https://eddb.io/archive/v5/systems_populated.json"

2) Import errors

System import:
( stack exec edda -- import -s eddb -t systems )

Couldn't parse system:
Object (fromList [("states",Array [Object (fromList [("name",String "None"),("id",Number 80.0)])]),("security_id",Number 64.0),("is_populated",Bool True),("government_id",Number 176.0),("reserve_type",Null),("z",Number 3899.15625),("primary_economy_id",Number 10.0),("power_state_id",Null),("edsm_id",Null),("controlling_minor_faction_id",Null),("allegiance_id",Number 5.0),("controlling_minor_faction",Null),("power_state",Null),("name",String "Drojo TO-E c26-2"),("updated_at",Number 1.590997876e9),("primary_economy",String "None"),("power",Null),("government",String "None"),("reserve_type_id",Null),("minor_faction_presences",Array [Object (fromList [("pending_states",Array []),("active_states",Array [Object (fromList [("name",String "None"),("id",Number 80.0)])]),("recovering_states",Array []),("minor_faction_id",Number 75798.0),("influence",Number 0.0),("happiness_id",Number 2.0)])]),("id",Number 3.7556891e7),("x",Number -2655.21875),("population",Number 0.0),("allegiance",String "None"),("simbad_ref",String ""),("security",String "Anarchy"),("needs_permit",Bool False),("y",Number -894.75)])
Importing into database...
Systems imported: 0
Total systems imported: 0

Station import:
( stack exec edda -- import -s eddb -t stations )

Couldn't parse system:
Object (fromList [("has_outfitting",Bool True),("states",Array [Object (fromList [("name",String "None"),("id",Number 80.0)])]),("settlement_security",Null),("max_landing_pad_size",String "M"),("settlement_size",Null),("government_id",Number 64.0),("body_id",Number 2.817451e7),("is_planetary",Bool False),("controlling_minor_faction_id",Number 76506.0),("has_blackmarket",Bool True),("allegiance_id",Number 4.0),("distance_to_star",Number 2798.0),("shipyard_updated_at",Null),("market_updated_at",Number 1.584744229e9),("has_rearm",Bool True),("name",String "Peake Station"),("updated_at",Number 1.584744229e9),("system_id",Number 6285877.0),("import_commodities",Array []),("type_id",Number 4.0),("economies",Array [String "Extraction",String "Refinery"]),("government",String "Corporate"),("id",Number 71463.0),("settlement_size_id",Null),("prohibited_commodities",Array [String "Narcotics",String "Tobacco",String "Combat Stabilisers",String "Imperial Slaves",String "Slaves",String "Battle Weapons"]),("has_refuel",Bool True),("selling_modules",Array [Number 738.0,Number 739.0,Number 743.0,Number 744.0,Number 748.0,Number 749.0,Number 753.0,Number 754.0,Number 768.0,Number 823.0,Number 824.0,Number 832.0,Number 834.0,Number 842.0,Number 845.0,Number 850.0,Number 851.0,Number 852.0,Number 854.0,Number 855.0,Number 860.0,Number 861.0,Number 867.0,Number 876.0,Number 878.0,Number 879.0,Number 881.0,Number 882.0,Number 885.0,Number 886.0,Number 888.0,Number 890.0,Number 891.0,Number 892.0,Number 896.0,Number 897.0,Number 901.0,Number 902.0,Number 906.0,Number 926.0,Number 927.0,Number 931.0,Number 932.0,Number 936.0,Number 937.0,Number 941.0,Number 961.0,Number 962.0,Number 966.0,Number 967.0,Number 971.0,Number 972.0,Number 976.0,Number 996.0,Number 997.0,Number 1001.0,Number 1002.0,Number 1006.0,Number 1007.0,Number 1011.0,Number 1012.0,Number 1016.0,Number 1036.0,Number 1037.0,Number 1041.0,Number 1042.0,Number 1046.0,Number 1047.0,Number 1051.0,Number 1052.0,Number 1056.0,Number 1076.0,Number 1077.0,Number 1081.0,Number 1082.0,Number 1086.0,Number 1087.0,Number 1091.0,Number 1092.0,Number 1096.0,Number 1116.0,Number 1117.0,Number 1121.0,Number 1122.0,Number 1126.0,Number 1127.0,Number 1131.0,Number 1151.0,Number 1152.0,Number 1156.0,Number 1157.0,Number 1161.0,Number 1162.0,Number 1166.0,Number 1167.0,Number 1171.0,Number 1191.0,Number 1192.0,Number 1193.0,Number 1199.0,Number 1200.0,Number 1201.0,Number 1207.0,Number 1208.0,Number 1212.0,Number 1213.0,Number 1217.0,Number 1245.0,Number 1246.0,Number 1247.0,Number 1248.0,Number 1249.0,Number 1250.0,Number 1251.0,Number 1254.0,Number 1255.0,Number 1256.0,Number 1257.0,Number 1262.0,Number 1263.0,Number 1270.0,Number 1286.0,Number 1287.0,Number 1288.0,Number 1290.0,Number 1291.0,Number 1294.0,Number 1298.0,Number 1306.0,Number 1307.0,Number 1308.0,Number 1326.0,Number 1327.0,Number 1333.0,Number 1338.0,Number 1339.0,Number 1344.0,Number 1345.0,Number 1352.0,Number 1368.0,Number 1369.0,Number 1373.0,Number 1374.0,Number 1375.0,Number 1377.0,Number 1379.0,Number 1395.0,Number 1400.0,Number 1404.0,Number 1414.0,Number 1415.0,Number 1419.0,Number 1420.0,Number 1424.0,Number 1434.0,Number 1435.0,Number 1439.0,Number 1440.0,Number 1444.0,Number 1526.0,Number 1528.0,Number 1577.0,Number 1578.0,Number 1579.0,Number 1581.0,Number 1583.0,Number 1587.0,Number 1594.0,Number 1595.0,Number 1599.0,Number 1600.0,Number 1604.0,Number 1637.0,Number 1785.0,Number 1787.0,Number 1789.0,Number 1791.0,Number 1809.0,Number 1810.0]),("has_repair",Bool True),("has_commodities",Bool True),("type",String "Industrial Outpost"),("selling_ships",Array []),("allegiance",String "Independent"),("settlement_security_id",Null),("export_commodities",Array []),("has_docking",Bool True),("has_shipyard",Bool False),("has_market",Bool True),("outfitting_updated_at",Number 1.584743745e9)])
Importing into database...
Stations imported: 0
Total stations imported: 0
Downloading EDDB commodities...
EDDB commodities downloaded
Importing station commodities
[ n: 0, nModified: 0, ok: 1.0]
Station commodities imported: 10

And the mongodb error:
ERROR:EDDA.Schema.OutfittingV2:2020-06-09 23:31:26 CEST - Couldn't parse outfitting v2: "Int_lifesupport_size1_class3"
ERROR:EDDA.Schema.OutfittingV2:2020-06-09 23:31:26 CEST - Couldn't parse outfitting v2: "Int_lifesupport_size1_class4"
ERROR:EDDA.Schema.OutfittingV2:2020-06-09 23:31:26 CEST - Couldn't parse outfitting v2: "Int_lifesupport_size1_class5"
ERROR:EDDA.Schema.OutfittingV2:2020-06-09 23:31:26 CEST - Couldn't parse outfitting v2: "Int_lifesupport_size2_class1"
ERROR:EDDA.Schema.OutfittingV2:2020-06-09 23:31:26 CEST - Couldn't parse outfitting v2: "Int_lifesupport_size2_class2"
ERROR:EDDA.Schema.OutfittingV2:2020-06-09 23:31:26 CEST - Couldn't parse outfitting v2: "Int_lifesupport_size2_class3"
ERROR:EDDA.Schema.OutfittingV2:2020-06-09 23:31:26 CEST - Couldn't parse outfitting v2: "Int_lifesupport_size2_class4"
ERROR:EDDA.Schema.OutfittingV2:2020-06-09 23:31:26 CEST - Couldn't parse outfitting v2: "Int_lifesupport_size2_class5"

Please investigate this errors please.

Thank you.

**Comment by troydm** [comment]
I haven't looked into this project in a while, it seems that EDDB file format and urls have changed, I'll take a look when I'll have time, also I'm surprised that someone is actually using something that I've wrote some 3 years ago and haven't touched in a while

**Comment by cs1ga** [comment]
Dear Troydm

Thank you for your work, and I am very grateful. I wait for your update.

King Regards,
Cs

**Comment by troydm** [comment]
@cs1ga I've fixed the import process but haven't checked if data collector still works or not, when I'll have more time I'll take a look, but for now you can try it out yourself

**Comment by cs1ga** [comment]
@troydm: Very Thank you. I going to see the changes.

**Comment by cs1ga** [comment]
Hi,

The initial import process has been run ready. :) Thank you.

The aggregator is running: 

INFO:EDDA.Subscriber:2020-06-11 21:56:40 CEST - saving commodities info Unktock / Baird Station
INFO:EDDA.Subscriber:2020-06-11 21:56:40 CEST - saving shipyard info Yoruba / Irvin Gateway

The aggregator get some error when the subject is a ship:

ERROR:EDDA.Schema.OutfittingV2:2020-06-11 21:56:33 CEST - Couldn't parse outfitting v2: "Int_shieldgenerator_size5_class5"
ERROR:EDDA.Schema.OutfittingV2:2020-06-11 21:56:33 CEST - Couldn't parse outfitting v2: "Int_shieldgenerator_size6_class1"
ERROR:EDDA.Schema.OutfittingV2:2020-06-11 21:56:33 CEST - Couldn't parse outfitting v2: "Int_shieldgenerator_size6_class2"
ERROR:EDDA.Schema.OutfittingV2:2020-06-11 21:56:33 CEST - Couldn't parse outfitting v2: "Int_shieldgenerator_size6_class3"
ERROR:EDDA.Schema.OutfittingV2:2020-06-11 21:56:33 CEST - Couldn't parse outfitting v2: "Int_shieldgenerator_size6_class3_f


Very-very thank you
King Regards,
cs1ga

**Comment by troydm** [comment]
@cs1ga I've improved outfitting v2 parsing, please get latest version and recompile, I'm closing this issue as it's not related to outfitting parsing, please report any parsing issues separately
